### ISSUE TITLE
Move top level Twitter elements to "twitter" package

### ISSUE THREAD

**Issue by keilw** [agorava/agorava-twitter#1]
I noticed the top level Twitter elements
Twitter.java
TwitterBaseService.java
TwitterLiteral.java
TwitterServicesHub.java

are currently in package "org.agorava". They should be in "org.agorava.twitter" instead, to avoid overlaps with other elements and modules.

**Comment by antoinesd** [comment]
Yes sure, but I did that in Seam Social to ease dnamic module discovery by the core. I guess it could be change now, but I wait to port Socializer to Agorava API to test these point further.
